USE test
CREATE TABLE employee(
	employeeId VARCHAR(18) PRIMARY KEY,
	employeeName VARCHAR(18),
	employeeType VARCHAR(18),
	`status` VARCHAR(18)
)
DROP TABLE employee
SELECT * FROM employee





CREATE	TABLE account(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(32) NOT NULL DEFAULT "",
  balance DOUBLE NOT NULL DEFAULT 0
) CHARACTER SET utf8

INSERT INTO account VALUES(NULL,'马云',3000);
INSERT INTO account VALUES(NULL,'马化腾',10000);

SELECT * FROM account